# Generated by Django 3.1 on 2020-11-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0013_auto_20200921_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridedata',
            name='endTime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ridedata',
            name='startTime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
