# Generated by Django 3.1 on 2020-11-04 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0014_auto_20201104_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridedata',
            name='heightList',
        ),
        migrations.RemoveField(
            model_name='ridedata',
            name='heightSampleRate',
        ),
        migrations.RemoveField(
            model_name='ridedata',
            name='tempList',
        ),
        migrations.RemoveField(
            model_name='ridedata',
            name='tempSampleRate',
        ),
    ]
