# Generated by Django 3.1 on 2020-11-04 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0016_auto_20201104_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zippeddataframe',
            old_name='rideId',
            new_name='ride',
        ),
    ]
