# Generated by Django 3.1 on 2020-11-04 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0017_auto_20201104_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zippeddataframe',
            old_name='dataType',
            new_name='type',
        ),
    ]
