# Generated by Django 3.1 on 2020-11-04 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0018_auto_20201104_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zippeddataframe',
            old_name='type',
            new_name='datatype',
        ),
    ]
