# Generated by Django 3.1 on 2020-11-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0020_auto_20201104_2223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZippedDataframe',
            new_name='DataframeCSV',
        ),
    ]
